export PATH=/opt/bin:/opt/go/bin:/opt/venv/bin:$PATH
# export LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH

export ZSH="/home/ubuntu/.oh-my-zsh"

export ZSH_THEME="agnoster"

export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"

export EDITOR="vim"

export GOROOT=/opt/go

plugins=(git history )

source $ZSH/oh-my-zsh.sh

#
# tmux alias from https://gist.github.com/lucaspiller/3377737
#
tm() {
  [[ -z "$1" ]] && { echo "usage: tm <session>" >&2; return 1; }
    tmux has -t $1 && tmux attach -d -t $1 || tmux new -s $1
}

# Source the users extra env
source ~/.env

alias pylint='/opt/venv/bin/pylint --rcfile=/home/ubuntu/.pylintrc'

alias gofmt='gofumpt'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
